version: '3.2'
services:
  flask:
    build: ./apiserver
    ports:
      - '5000:5000'
    depends_on:
      - postgres
      - rabbit
      - worker
    environment:
      - DB_URL=${DB_URL}
      - BROKER_URL=${BROKER_URL}
  worker:
    build: ./celery
    depends_on:
      - postgres
      - rabbit
    environment:
      - DB_URL=${DB_URL}
      - DL_DIR=${DL_DIR}
      - BROKER_URL=${BROKER_URL}
    volumes:
      - type: bind
        source: ${SOURCE_DIR}
        target: ${DL_DIR}
  rabbit:
    image: rabbitmq:latest
  postgres:
    image: postgres:10-alpine
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:${ES_VERSION}
    ports:
      - '9200:9200'
    environment:
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
    networks:
      - esnet
  filebeat:
    build:
      context: ./elastic_stack
      args:
        - ES_VERSION=${ES_VERSION}
    user: root
    depends_on:
      - elasticsearch
    networks:
      - esnet
    environment:
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
    volumes:
      - type: bind
        source: ${LOG_PATH}
        target: /var/lib/docker/containers
  kibana:
    image: docker.elastic.co/kibana/kibana-oss:${ES_VERSION}
    ports: 
      - '5601:5601'
    depends_on:
      - elasticsearch
    networks:
      - esnet
networks: 
  esnet:
