version: '3.2'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:${ES_VERSION}
    ports:
      - '9200:9200'
    environment:
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
  logstash:
    image: docker.elastic.co/logstash/logstash-oss:${ES_VERSION}
    ports:
      - '12201:12201/udp'
    depends_on:
      - elasticsearch
    environment:
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
    volumes:
      - type: bind
        source: ${CONF_PATH}
        target: /usr/share/logstash/pipeline/
  kibana:
    image: docker.elastic.co/kibana/kibana-oss:${ES_VERSION}
    ports: 
      - '5601:5601'
    depends_on:
      - elasticsearch