filebeat.prospectors:
  - type: log
    paths:
      - /var/lib/docker/containers/*/*.log
    json.message_key: log
    json.keys_under_root: true
output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]
  username: "elastic"
  password: ${ELASTIC_PASSWORD}